# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booklist.Kategori'),
        ),
    ]
